apiVersion: batch/v1
kind: CronJob
metadata:
  name: aimail
spec:
  schedule: "0 0 1 * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: aimail
              image: ghcr.io/skymoore/aima-emailer:latest
              args:
                - --full-name
                - "Your Name"
                - --nationality
                - "Lituanian"
                - --appointment-date
                - "2025-01-01"
                - --service-location
                - "Loja AIMA - Rio Tinto"
                - --passport-number
                - "1234567890"
                - --correct-address
                - "Somewhere in lisbon, 1234-222"
                - --contact-number
                - "+351 123 456 789"
                - --from-email
                - "my-address@example.com"
                - --to-email
                - "aima@aima.gov.pt"
                - --subject
                - "Pedido de Atualização de Morada"
                - --attachment
                - "assets/passport.png"
                - --attachment
                - "assets/aima-temp-id.jpg"
                - --attachment
                - "assets/rental-contract.pdf"
              envFrom:
                - secretRef:
                    name: aimail-env
